### ISSUE TITLE
make path to mysql.sock configurable

### ISSUE THREAD

**Issue by kotowicz** [datajoint/mym#8]
currently this is hard coded:
```
$ grep sock -R * | grep tmp
mysql-connector/include/mysql_version.h:#define MYSQL_UNIX_ADDR            "/tmp/mysql.sock"
```
on Ubuntu the mysqld.sock file is (at least on 12.04) in `/var/run/mysqld/mysqld.sock` instead.
ideally one could make this a config option so that mym could be configured on the fly to use the correct file/path.

**Comment by dimitri-yatsenko** [comment]
Closing as invalid.
