### ISSUE TITLE
Cannot access blob data inserted with older version of `mym`

### ISSUE THREAD

**Issue by kabilar** [datajoint/mym#86]
### Description
Cannot open blob fields that are inserted with an old version of `mym` with either a newer version of `mym` or `datajoint-python`>=0.13.

### Reproducibility

Access with `mym` version 1.36 works well.
- OS  Windows
- MATLAB 2019b
- MySQL 5.1.73-log
- mym 1.36 (hosted [here](https://github.com/Brody-Lab/ExperPort/tree/master/MySQLUtility))

```
mym('version')
Matlab<->MySQL connector v1.36
data = mym('select protocol_data from bdata.sessions where sessid=816988')

data =

  struct with fields:

    protocol_data: {[1×1 struct]}
```

Access with `mym` version 2.8.2 does not work.
- OS  MAC
- MATLAB 2020a
- MariaDB 10.2.33 (This is a copy of the tables used on the original database.)
- mYm 2.8.2

```
mym('version')
mYm version 2.8.2
data = mym('select protocol_data from bdata.sessions where sessid=816988')
Out of memory.
```

Access with `datajoint-python` version 0.13.2 does not work.
- OS  MAC
- MariaDB 10.2.33 (This is a copy of the tables used on the original database.)
- DataJoint Python 0.13.2

Retrieves a byte string that am not sure how to decode.
```
subject_session_key = {'sessid': 816986}
session_data = (bdata.Sessions & subject_session_key).fetch('protocol_data', as_dict=True)

[{'protocol_data': b'ZL123\x007\x04\x00\x00x\x9c\xcb\x8d\xcce\x08fb```\x84b> .\xceLI-f\xc8\xc8,a\xc8\xc9OfH.(a\x08(\xca\xf7\x89O\xce\x033\x82\xc0\x0c\xc7\xbc\x12\x1f\x18#\x08&\xe5\x13_\x90Z\x94\x06Q\x04f\x81U\xc1XP1\xdf\xcc<?Og\x06\xdf\xc4\n\x10\xe5\t\xb4\xcf\x11\xe4\x00)\xa8\x03X\x18  \x87\x0c\xf8\x14\xdd06\x06R\xc0\x07{T\x1a]\x1c\x97zB|\\4\xb1\xea0\xf5\xe1\x0c\xb5\x022 \x81P\xfb\xf1\x7f\xb8\xd0\xb20\x8f\xc2\x12;\xaaG\xad\x1c\x08(``\xa0\xa1\x82$\xf52 zdO\xc0\x04\x82\xbe\xa0D\xc1\x9f\x95\x1f/\xf9&\x05\xe0v\x03L\x01\x00w"\x9b\xf2'}]
```

Thanks!

**Comment by Alvalunasan** [comment]
Struct representation of query
`data = mym('select protocol_data from bdatatest.sessions where sessid=822635')`
`data = 
  struct with fields:
    protocol_data: {[1×1 struct]}`
    
`data.protocol_data{1, 1}.stage = 'Stage 10'`
`data.protocol_data{1, 1}.tasks = 'ddddddd'`
`data.protocol_data{1, 1}.sides = 'llllrrl'`
`data.protocol_data{1, 1}.hits = [NaN,1,1,0,1,0,NaN]`

Hex representation of query
`data = mym('select hex(protocol_data) as hexo from bdatatest.sessions where sessid=822635')`
`data.hexo{1,1} = '6D596D00530200000001000000010000000400000068697473007369646573007461736B73007374616765004D000000410200000001000000070000000600000000000000000000000000F8FF000000000000F03F000000000000F03F0000000000000000000000000000F03F0000000000000000000000000000F8FF230000004102000000010000000700000004000000000000006C006C006C006C00720072006C002300000041020000000100000007000000040000000000000064006400640064006400640064002500000041020000000100000008000000040000000000000053007400610067006500200031003000'`
